# Latest 'n' Greatest
update
upgrade

# Install GNU core utilities (those that come with OS X are outdated)
install coreutils
install findutils
install gnu-sed --default-names
install moreutils

# Install GRC for coloring
install grc

# Install wget with IRI support
install wget --enable-iri

# Install more recent versions of some OS X tools
install vim --override-system-vi

# Install other useful binaries
install git
install ngrep
install node
install rename
install the_silver_searcher
install trash
install tree

# Remove outdated versions from the cellar
cleanup
